### ISSUE TITLE
Continuous reconnect when not using automatic recovery

### ISSUE THREAD

**Issue by milgner** [eclipse-vertx/vertx-rabbitmq-client#9]
### Version
4.4.0

### Context

Setting up the RabbitMQ client like described in the documentation:

```
RabbitMQOptions options = new RabbitMQOptions();
options.setAutomaticRecoveryEnabled(false);
options.setReconnectAttempts(Integer.MAX_VALUE);
options.setReconnectInterval(500);
```

I can see in the logs, that it does re-connect *every* 500ms even if there aren't any issues with the connection.

After changing it to

```
RabbitMQOptions options = new RabbitMQOptions();
options.setAutomaticRecoveryEnabled(true);
options.setReconnectAttempts(0);
```

the application works just fine with the client.
There aren't any logs that indicate something could be wrong with the first setup, though.

### Do you have a reproducer?

No reproducer, but if it helps I'll try building one with test containers? (there'd have to be a RabbitMQ server included, I guess) 

### Steps to reproduce

See above :slightly_smiling_face: 

### Extra

* RabbitMQ 3.11.1
* `Linux 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64 GNU/Linux`
* OpenJDK 17

**Comment by Yaytay** [comment]
Well that's not good.
Please can you try to create a reproducer?
If not, let me have details of the connection (everything except your credentials) and logs.
Thanks.

**Comment by milgner** [comment]
Unfortunately, my first attempt at reproducing it in a separate project wasn't successful... I'll try it again with the actual RabbitMQ instance I was using before and trying to add more of the original setup code (more queue declarations, bindings etc). Gonna need a couple more days, though.

**Comment by milgner** [comment]
Tried to reproduce it with my original program again and for some reason the observed behaviour seems to be gone now - everything works as expected. So I'm gonna close this... Thank you for your work in providing a great library!
